config/routes.rb
Rails.application.routes.draw do
  get 'documentaryfilms/index' 
  get 'documentaryfilms/new'

  get 'series/index' 
  get 'series/new'
  
  get 'movies/index'
  get 'movies/new'

  post "/documentaryfilms/create"=>"documentaryfilms#create"
  post "/series/create"=>"series#create"
  post "/movies/create"=>"movies#create"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "movies#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentaryfilm.rb
class Documentaryfilm < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/models/serie.rb
class Serie < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentaryfilms_controller.rb
class DocumentaryfilmsController < ApplicationController
  def index
    @documentaryfilms= Documentaryfilm.all
  end

  def create
    @documentaryfilm= Documentaryfilm.new(documentaryfilms_params)
    if @documentaryfilm.save 
      redirect_to documentaryfilms_index_path
    else
      render :new 
    end
  end

  def new
    @documentaryfilm= Documentaryfilm.new 
  end

  def documentaryfilms_params
    params.require(:documentaryfilm).permit(:name, :synopsis, :director)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies= Movie.all
  end

  def create
    @movie= Movie.new(movies_params)
    if @movie.save 
      redirect_to movies_index_path
    else
      render :new 
    end
  end

  def new
    @movie= Movie.new 
  end

  def movies_params
    params.require(:movie).permit(:name, :synopsis, :director)
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @series= Serie.all
  end

  def create
    @serie= Serie.new(series_params)
    if @serie.save 
      redirect_to series_index_path
    else
      render :new 
    end
  end

  def new
    @serie= Serie.new 
  end

  def series_params
    params.require(:serie).permit(:name, :synopsis, :director)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentaryfilms_helper.rb
module DocumentaryfilmsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/documentaryfilms/create.html.erb
<h1>Documentaryfilms#create</h1>
<p>Find me in app/views/documentaryfilms/create.html.erb</p>

app/views/documentaryfilms/index.html.erb
<h1>Documentaryfilms#index</h1>
<p>Find me in app/views/documentaryfilms/index.html.erb</p>

<%= link_to 'Ingresar un nuevo Documentary Film', documentaryfilms_new_path %>

<div>
    <table class="table table-dark table-striped-columns">
        <thead>
            <tr>
                <th scope="col">N°</th>
                <th scope="col">Nombre del Documental</th>
                <th scope="col">Sinopsis</th>
                <th scope="col">Director</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            <% @documentaryfilms.each do |documentaryfilm| %>
            <tr>
                <th scope="row"><%= documentaryfilm.id %></th>
                <td><%= documentaryfilm.name %></>
                <td><%= documentaryfilm.synopsis %></td>
                <td><%= documentaryfilm.director %></td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>

app/views/documentaryfilms/new.html.erb
<h1>Documentaryfilms#new</h1>
<p>Find me in app/views/documentaryfilms/new.html.erb</p>
<h1>Nuevo Documentary Film</h1>
<%= form_with url: documentaryfilms_create_path, model: @documentaryfilm, method: :post do |form| %>
  <div>
    <%= form.label :name, "Ingresa Tu Documentary Film" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :synopsis, "Cuentame de tu Documentary" %>
    <%= form.text_area :synopsis %>
  </div>
  <div>
    <%= form.label :director, "Dime el Director" %>
    <%= form.text_field :director %>
  </div>
  <div>
    <%= form.submit "Guardar" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css', crossorigin: 'anonymous' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container">
        <a class="navbar-brand" href="#">Cinerama</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Movies", movies_index_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Series", series_index_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Documentary Films", documentaryfilms_index_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

<div class="container">
  <%= yield %>
</div>
    



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/index.html.erb
<h1>Movies#index</h1>
<p>Find me in app/views/movies/index.html.erb</p>

<%= link_to 'Ingresar una nueva Movie', movies_new_path %>

<div>
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">N°</th>
                <th scope="col">Nombre de la Movie</th>
                <th scope="col">Sinopsis</th>
                <th scope="col">Director</th>
            </tr>
        </thead>
        <tbody>
            <% @movies.each do |movie| %>
            <tr>
                <th scope="row"><%= movie.id %></th>
                <td><%= movie.name %></>
                <td><%= movie.synopsis %></td>
                <td><%= movie.director %></td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>

app/views/movies/new.html.erb
<h1>Movies#new</h1>
<p>Find me in app/views/movies/new.html.erb</p>
<h1>Nueva Movie</h1>
<%= form_with url: movies_create_path, model: @movie, method: :post do |form| %>
  <div>
    <%= form.label :name, "Ingresa Tu Movie" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :synopsis, "Cuentame de tu Movie" %>
    <%= form.text_area :synopsis %>
  </div>
  <div>
    <%= form.label :director, "Dime el Director" %>
    <%= form.text_field :director %>
  </div>
  <div>
    <%= form.submit "Guardar" %>
  </div>
<% end %>

app/views/series/create.html.erb
<h1>Series#create</h1>
<p>Find me in app/views/series/create.html.erb</p>

app/views/series/index.html.erb
<h1>Series#index</h1>
<p>Find me in app/views/series/index.html.erb</p>

<%= link_to 'Ingresar una nueva Serie', series_new_path %>

<div>
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">N°</th>
                <th scope="col">Nombre de la Serie</th>
                <th scope="col">Sinopsis</th>
                <th scope="col">Director</th>
            </tr>
        </thead>
        <tbody>
            <% @series.each do |serie| %>
            <tr>
                <th scope="row"><%= serie.id %></th>
                <td><%= serie.name %></>
                <td><%= serie.synopsis %></td>
                <td><%= serie.director %></td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>

app/views/series/new.html.erb
<h1>Series#new</h1>
<p>Find me in app/views/series/new.html.erb</p>
<h1>Nueva Serie</h1>
<%= form_with url: series_create_path, model: @serie, method: :post do |form| %>
  <div>
    <%= form.label :name, "Ingresa Tu Serie" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :synopsis, "Cuentame de tu serie" %>
    <%= form.text_area :synopsis %>
  </div>
  <div>
    <%= form.label :director, "Dime el Director" %>
    <%= form.text_field :director %>
  </div>
  <div>
    <%= form.submit "Guardar" %>
  </div>
<% end %>